import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "y/utils/api";

const Home: NextPage = () => {
  const { isSignedIn, user } = useUser();

  const accessToken = api.example.getUserAccessToken.useQuery({
    userId: user?.id || "",
    provider: "google",
  });

  console.log(accessToken.data, "access token");

  return (
    <>
      <Head>
        <title>Books&Quotes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
